//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 15.0.28307.421
// 
namespace 课程表UWP.CloudService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CloudService.kechengbiaoSoap")]
    public interface kechengbiaoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Upload", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<课程表UWP.CloudService.UploadResponse> UploadAsync(课程表UWP.CloudService.UploadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> DeleteFileAsync(string username, string password, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetScheluleListOfUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<课程表UWP.CloudService.Schedule[]> GetScheluleListOfUserAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetScheluleListNearby", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<课程表UWP.CloudService.Schedule[]> GetScheluleListNearbyAsync(string 省份, string 城市, int m, int n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProvinceScheluleList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<课程表UWP.CloudService.Schedule[]> GetProvinceScheluleListAsync(string 省份, int m, int n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<课程表UWP.CloudService.GetFileResponse> GetFileAsync(课程表UWP.CloudService.GetFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DownloadClassById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<课程表UWP.CloudService.DownloadClassByIdResponse> DownloadClassByIdAsync(课程表UWP.CloudService.DownloadClassByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DownloadClassByName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<课程表UWP.CloudService.DownloadClassByNameResponse> DownloadClassByNameAsync(课程表UWP.CloudService.DownloadClassByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectMN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<课程表UWP.CloudService.Schedule[]> SelectMNAsync(int m, int n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchScheduleName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<课程表UWP.CloudService.Schedule[]> SearchScheduleNameAsync(string scheduleName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDocumentLenById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> GetDocumentLenByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDocumentLenByName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> GetDocumentLenByNameAsync(string classtitle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendEmailCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<课程表UWP.CloudService.ResponseResult> SendEmailCodeAsync(string email);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string usernameField;
        
        private string qQUserField;
        
        private string passwordField;
        
        private string nicknameField;
        
        private string emailField;
        
        private string photoField;
        
        private bool validateField;
        
        private bool isVipField;
        
        private int levelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string QQUser {
            get {
                return this.qQUserField;
            }
            set {
                this.qQUserField = value;
                this.RaisePropertyChanged("QQUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Nickname {
            get {
                return this.nicknameField;
            }
            set {
                this.nicknameField = value;
                this.RaisePropertyChanged("Nickname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Photo {
            get {
                return this.photoField;
            }
            set {
                this.photoField = value;
                this.RaisePropertyChanged("Photo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool Validate {
            get {
                return this.validateField;
            }
            set {
                this.validateField = value;
                this.RaisePropertyChanged("Validate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool IsVip {
            get {
                return this.isVipField;
            }
            set {
                this.isVipField = value;
                this.RaisePropertyChanged("IsVip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int Level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
                this.RaisePropertyChanged("Level");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResponseResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool isSuccessField;
        
        private string msgAlertField;
        
        private string urlNavField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool IsSuccess {
            get {
                return this.isSuccessField;
            }
            set {
                this.isSuccessField = value;
                this.RaisePropertyChanged("IsSuccess");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MsgAlert {
            get {
                return this.msgAlertField;
            }
            set {
                this.msgAlertField = value;
                this.RaisePropertyChanged("MsgAlert");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UrlNav {
            get {
                return this.urlNavField;
            }
            set {
                this.urlNavField = value;
                this.RaisePropertyChanged("UrlNav");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Schedule : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private Location locationField;
        
        private string scheduleNameField;
        
        private string filePathField;
        
        private System.DateTime createTimeField;
        
        private string descriptionField;
        
        private string userNameField;
        
        private string passwordField;
        
        private int statisField;
        
        private string imageUrlField;
        
        private string recommendField;
        
        private string tagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Location location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ScheduleName {
            get {
                return this.scheduleNameField;
            }
            set {
                this.scheduleNameField = value;
                this.RaisePropertyChanged("ScheduleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FilePath {
            get {
                return this.filePathField;
            }
            set {
                this.filePathField = value;
                this.RaisePropertyChanged("FilePath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime CreateTime {
            get {
                return this.createTimeField;
            }
            set {
                this.createTimeField = value;
                this.RaisePropertyChanged("CreateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int Statis {
            get {
                return this.statisField;
            }
            set {
                this.statisField = value;
                this.RaisePropertyChanged("Statis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ImageUrl {
            get {
                return this.imageUrlField;
            }
            set {
                this.imageUrlField = value;
                this.RaisePropertyChanged("ImageUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Recommend {
            get {
                return this.recommendField;
            }
            set {
                this.recommendField = value;
                this.RaisePropertyChanged("Recommend");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
                this.RaisePropertyChanged("Tag");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Location : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string provinceField;
        
        private string cityField;
        
        private string districtField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Province {
            get {
                return this.provinceField;
            }
            set {
                this.provinceField = value;
                this.RaisePropertyChanged("Province");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string District {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
                this.RaisePropertyChanged("District");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Upload", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public 课程表UWP.CloudService.UserInfo userInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public 课程表UWP.CloudService.Location location;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string filename;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string description;
        
        public UploadRequest() {
        }
        
        public UploadRequest(课程表UWP.CloudService.UserInfo userInfo, 课程表UWP.CloudService.Location location, byte[] data, string filename, string description) {
            this.userInfo = userInfo;
            this.location = location;
            this.data = data;
            this.filename = filename;
            this.description = description;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UploadResult;
        
        public UploadResponse() {
        }
        
        public UploadResponse(string UploadResult) {
            this.UploadResult = UploadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int id;
        
        public GetFileRequest() {
        }
        
        public GetFileRequest(string username, int id) {
            this.username = username;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetFileResult;
        
        public GetFileResponse() {
        }
        
        public GetFileResponse(byte[] GetFileResult) {
            this.GetFileResult = GetFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadClassById", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadClassByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        public DownloadClassByIdRequest() {
        }
        
        public DownloadClassByIdRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadClassByIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadClassByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] DownloadClassByIdResult;
        
        public DownloadClassByIdResponse() {
        }
        
        public DownloadClassByIdResponse(byte[] DownloadClassByIdResult) {
            this.DownloadClassByIdResult = DownloadClassByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadClassByName", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadClassByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string scheduleName;
        
        public DownloadClassByNameRequest() {
        }
        
        public DownloadClassByNameRequest(string scheduleName) {
            this.scheduleName = scheduleName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadClassByNameResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadClassByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] DownloadClassByNameResult;
        
        public DownloadClassByNameResponse() {
        }
        
        public DownloadClassByNameResponse(byte[] DownloadClassByNameResult) {
            this.DownloadClassByNameResult = DownloadClassByNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface kechengbiaoSoapChannel : 课程表UWP.CloudService.kechengbiaoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class kechengbiaoSoapClient : System.ServiceModel.ClientBase<课程表UWP.CloudService.kechengbiaoSoap>, 课程表UWP.CloudService.kechengbiaoSoap {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public kechengbiaoSoapClient() : 
                base(kechengbiaoSoapClient.GetDefaultBinding(), kechengbiaoSoapClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.kechengbiaoSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public kechengbiaoSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(kechengbiaoSoapClient.GetBindingForEndpoint(endpointConfiguration), kechengbiaoSoapClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public kechengbiaoSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(kechengbiaoSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public kechengbiaoSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(kechengbiaoSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public kechengbiaoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<课程表UWP.CloudService.UploadResponse> 课程表UWP.CloudService.kechengbiaoSoap.UploadAsync(课程表UWP.CloudService.UploadRequest request) {
            return base.Channel.UploadAsync(request);
        }
        
        public System.Threading.Tasks.Task<课程表UWP.CloudService.UploadResponse> UploadAsync(课程表UWP.CloudService.UserInfo userInfo, 课程表UWP.CloudService.Location location, byte[] data, string filename, string description) {
            课程表UWP.CloudService.UploadRequest inValue = new 课程表UWP.CloudService.UploadRequest();
            inValue.userInfo = userInfo;
            inValue.location = location;
            inValue.data = data;
            inValue.filename = filename;
            inValue.description = description;
            return ((课程表UWP.CloudService.kechengbiaoSoap)(this)).UploadAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<string> DeleteFileAsync(string username, string password, int id) {
            return base.Channel.DeleteFileAsync(username, password, id);
        }
        
        public System.Threading.Tasks.Task<课程表UWP.CloudService.Schedule[]> GetScheluleListOfUserAsync(string username) {
            return base.Channel.GetScheluleListOfUserAsync(username);
        }
        
        public System.Threading.Tasks.Task<课程表UWP.CloudService.Schedule[]> GetScheluleListNearbyAsync(string 省份, string 城市, int m, int n) {
            return base.Channel.GetScheluleListNearbyAsync(省份, 城市, m, n);
        }
        
        public System.Threading.Tasks.Task<课程表UWP.CloudService.Schedule[]> GetProvinceScheluleListAsync(string 省份, int m, int n) {
            return base.Channel.GetProvinceScheluleListAsync(省份, m, n);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<课程表UWP.CloudService.GetFileResponse> 课程表UWP.CloudService.kechengbiaoSoap.GetFileAsync(课程表UWP.CloudService.GetFileRequest request) {
            return base.Channel.GetFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<课程表UWP.CloudService.GetFileResponse> GetFileAsync(string username, int id) {
            课程表UWP.CloudService.GetFileRequest inValue = new 课程表UWP.CloudService.GetFileRequest();
            inValue.username = username;
            inValue.id = id;
            return ((课程表UWP.CloudService.kechengbiaoSoap)(this)).GetFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<课程表UWP.CloudService.DownloadClassByIdResponse> 课程表UWP.CloudService.kechengbiaoSoap.DownloadClassByIdAsync(课程表UWP.CloudService.DownloadClassByIdRequest request) {
            return base.Channel.DownloadClassByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<课程表UWP.CloudService.DownloadClassByIdResponse> DownloadClassByIdAsync(int id) {
            课程表UWP.CloudService.DownloadClassByIdRequest inValue = new 课程表UWP.CloudService.DownloadClassByIdRequest();
            inValue.id = id;
            return ((课程表UWP.CloudService.kechengbiaoSoap)(this)).DownloadClassByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<课程表UWP.CloudService.DownloadClassByNameResponse> 课程表UWP.CloudService.kechengbiaoSoap.DownloadClassByNameAsync(课程表UWP.CloudService.DownloadClassByNameRequest request) {
            return base.Channel.DownloadClassByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<课程表UWP.CloudService.DownloadClassByNameResponse> DownloadClassByNameAsync(string scheduleName) {
            课程表UWP.CloudService.DownloadClassByNameRequest inValue = new 课程表UWP.CloudService.DownloadClassByNameRequest();
            inValue.scheduleName = scheduleName;
            return ((课程表UWP.CloudService.kechengbiaoSoap)(this)).DownloadClassByNameAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<课程表UWP.CloudService.Schedule[]> SelectMNAsync(int m, int n) {
            return base.Channel.SelectMNAsync(m, n);
        }
        
        public System.Threading.Tasks.Task<课程表UWP.CloudService.Schedule[]> SearchScheduleNameAsync(string scheduleName) {
            return base.Channel.SearchScheduleNameAsync(scheduleName);
        }
        
        public System.Threading.Tasks.Task<int> GetDocumentLenByIdAsync(int id) {
            return base.Channel.GetDocumentLenByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<int> GetDocumentLenByNameAsync(string classtitle) {
            return base.Channel.GetDocumentLenByNameAsync(classtitle);
        }
        
        public System.Threading.Tasks.Task<课程表UWP.CloudService.ResponseResult> SendEmailCodeAsync(string email) {
            return base.Channel.SendEmailCodeAsync(email);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.kechengbiaoSoap)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.kechengbiaoSoap)) {
                return new System.ServiceModel.EndpointAddress("https://www.songshizhao.com/apps/课程表UWP/kechengbiao.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return kechengbiaoSoapClient.GetBindingForEndpoint(EndpointConfiguration.kechengbiaoSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return kechengbiaoSoapClient.GetEndpointAddress(EndpointConfiguration.kechengbiaoSoap);
        }
        
        public enum EndpointConfiguration {
            
            kechengbiaoSoap,
        }
    }
}
